name: Unity CI

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  tests:
    name: Edit/Play Mode Tests (Unity)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2022.3.62f1
          testMode: all
          artifactsPath: artifacts

  validate:
    name: Project Validation (Editor checks)
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Unity - Run editor validation
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2022.3.62f1
          testMode: editmode
          customParameters: >
            -executeMethod TavernSim.Editor.CI.ProjectValidation.Run
